kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: dev
  name: viewrolebinding
subjects:
- kind: ServiceAccount
  name: ken
  apiGroup: ""
roleRef:
  kind: Role
  name: view
  apiGroup: rbac.authorization.k8s.io
