apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 50%
  template:
    metadata:
      name: web
      labels:
        app: web
    spec:
      volumes:
      - name: app
        emptyDir: {}
      containers:
      - name: web
        image: alexeyyakovlev1982/docker_simple_py_http_server_yakovlev
        volumeMounts:
        - name: app
          mountPath: /app
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000
        livenessProbe:
          tcpSocket:
            port: 8000
      initContainers:
      - name: init-web
        image: busybox:1.31
        command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
        volumeMounts:
        - name: app
          mountPath: /app

