apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: prometheus
subjects:
- kind: Group # User/Group/ServiceAccount
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
- kind: Group # User/Group/ServiceAccount
  name: system:unauthenticated
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
