apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    operation: Apply
  name: cluster-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: bob
  namespace: default
