kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adminrolebinding
subjects:
- kind: ServiceAccount
  name: bob
  apiGroup: ""
roleRef:
  kind: Role
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
