repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: jetstack
    url: https://charts.jetstack.io
  - name: harbor
    url: https://helm.goharbor.io

releases:
  - name: nginx-ingress 
    namespace: nginx-ingress 
    chart: stable/nginx-ingress 
    version: 1.41.3
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.1.0
    args:
      - "--set installCRDs=true"
  - name: harbor
    namespace: harbor
    chart: harbor/harbor
    version: 1.1.2
    values:
      - ../harbor/values.yaml
